version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi-backend
    image: kibwa14/secondproject_fastapi:latest
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # env_file:
    #   - ./fastapi-backend/.env
    networks:
      - app-network

  nodejs:
    build:
      context: ./node-backend
    image: kibwa14/secondproject_nodejs:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge