version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  nodejs:
    build:
      context: ./node-backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge