apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-yb         # 배포 리소스의 이름
spec:
  replicas: 1                     # 원하는 파드 수 (보통 1개부터 시작)
  selector:
    matchLabels:
      app: nodejs                 # 이 deployment가 관리할 pod 라벨
  template:
    metadata:
      labels:
        app: nodejs               # 위 selector에 맞추기 위해 pod에 이 라벨을 붙임
    spec:
      containers:
        - name: nodejs
          image: kibwa14/secondproject_nodejs:latest
          ports:
            - containerPort: 3000               # Node.js 앱이 리슨 중인 포트
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-yb            # Node.js 서비스 이름 (프론트에서 접근용)
spec:
  type: NodePort              # 외부에 노출되는 서비스 (클라우드 환경에서 사용)
  selector:
    app: nodejs                   # 위의 Deployment 파드를 선택
  ports:
    - protocol: TCP
      port: 80                    # 외부에서 접근할 포트 (브라우저에서 접속 시 사용)
      targetPort: 3000           # 실제 컨테이너에서 Node.js가 리슨하는 포트
      nodePort: 31000